#!/bin/bash
export SAVE_ROOT="runs/baseline_static_saute_rerun"
echo "=== SautePPO Retraining Status ===" 
echo "Date: $(date)"
echo ""
echo "=== Jobs Status ==="
squeue -u "$USER" | grep saute || echo "No saute jobs running"
echo ""
echo "=== Completed EvalPacks ==="
find "$SAVE_ROOT" -name "evalpack" -type d | wc -l | xargs echo "EvalPacks found:"
echo "Expected: 6 (3 seeds × 2 modes)"
echo ""
echo "=== Directory Structure ==="
ls -la "$SAVE_ROOT" 2>/dev/null || echo "Save directory not created yet"
echo ""
echo "=== Latest Log Activity ==="
ls -lat logs/*saute* 2>/dev/null | head -3 || echo "No saute logs yet"
