#!/bin/bash
export SAVE_ROOT="runs/pcs_smoke_1seed"
echo "=== PCS Grid Training Status ==="
echo "Date: $(date)"
echo ""
echo "=== Jobs Status ==="
squeue -u "$USER" | grep pcs || echo "No PCS grid jobs running"
echo ""
echo "=== Completed EvalPacks ==="
find "$SAVE_ROOT" -name "evalpack" -type d 2>/dev/null | wc -l | xargs echo "EvalPacks found:"
echo "Expected: 30 (5 algos × 2 modes × 3 PCS)"
echo ""
echo "=== Directory Structure ==="
ls -la "$SAVE_ROOT" 2>/dev/null || echo "Save directory not created yet"
echo ""
echo "=== PCS Distribution ==="
find "$SAVE_ROOT" -type d -name "*seed0" 2>/dev/null | sed 's|.*/||' | sort | uniq -c || echo "No runs yet"
